// 客户端安全的站点配置（不依赖 Node.js fs）
export type Lang = "zh" | "en";

export interface PostFrontmatter {
  title: string;
  date: string;
  draft?: boolean;
  author?: string;
  tags?: string[];
  categories?: string[];
  summary?: string;
  description?: string;
  pinned?: boolean;
  /* 卡组内文章的手动排序号；不写则按文件名数字前缀排 */
  order?: number;
  /* 作为「关于」文章：正文会渲染在首页首屏，并不再出现在下方展示位里 */
  about?: boolean;
  pinnedDescription?: string;
  hiddenInHomeList?: boolean;
  showToc?: boolean;
  cover?: { image?: string; caption?: string; hidden?: boolean; relative?: boolean };
  references?: { title: string; url?: string; author?: string; year?: string }[];
  keywords?: string[];
  canonicalURL?: string;
}

export interface Post {
  slug: string;
  lang: Lang;
  title: string;
  date: string;
  author?: string;
  tags: string[];
  categories: string[];
  summary: string;
  description?: string;
  pinned: boolean;
  about: boolean;
  /* 所属卡组的目录名；不属于任何卡组时为 undefined */
  group?: string;
  /* 卡组内的排序号（frontmatter 的 order） */
  order?: number;
  /* 卡片右侧缩略图：优先 frontmatter 的 cover.image，否则取正文第一张图。
     两者都没有则为 undefined，卡片不渲染图片。 */
  thumbnail?: string;
  pinnedDescription?: string;
  hiddenInHomeList: boolean;
  showToc: boolean;
  cover?: PostFrontmatter["cover"];
  references?: PostFrontmatter["references"];
  keywords?: string[];
  content: string;
  filePath: string;
  wordCount: number;
  isAI: boolean;
}

/* ===== 卡组（文章组） =====
   由 content/<lang>/posts/<组名>/_index.md 标记，同目录下的 .md 即组内文章。
   组本身没有日期，用组内最新文章的时间去列表里定位。 */
export interface PostGroup {
  /** 目录名，也是 URL 片段 */
  slug: string;
  lang: Lang;
  title: string;
  description?: string;
  /** 组内最新一篇文章的日期，用于列表排序 */
  date: string;
  /** 封面图：_index.md 的 cover.image，填满卡片边框内部 */
  cover?: string;
  /** 已按 order / 文件名前缀排好序的组内文章 */
  posts: Post[];
  wordCount: number;
}

export const SITE = {
  title: "wunai's blog",
  author: "wunai",
  url: "https://blog.wunai.top",
  defaultLang: "zh" as Lang,
  description: "学习笔记与生活思考：数学、物理、化学、医学、技术文章集合",
  /* ===== 联系方式：邮箱 / GitHub / 本仓库 / 社交账号 =====
     文案（标签、说明、仓库名）在下面 i18n 里，中英文各一份；
     这里只放与语言无关的地址与账号 */
  contact: {
    email: "3234319738@qq.com",
    github: "https://github.com/wunai-xc",
    repo: "https://github.com/wunai-xc/wunai-blog",
    /* 可直接跳转的两个账号 */
    bilibili: "https://b23.tv/2alhnm5",
    bilibiliName: "WUNAI-XC",
    youtube: "https://youtube.com/@wunai-xc",
    youtubeName: "@wunai-xc",
    /* 只能展示、无法链接的：微信 ID；Discord 通过邮箱加好友，说明文案在 i18n */
    wechat: "wunaixc",
  },
  homeInfo: {
    zh: { title: "Hi there", content: "欢迎来到我的博客，这里记录我的学习笔记与生活思考。" },
    en: { title: "Hi there", content: "Welcome to my blog — notes on tech and life." },
  },
  menu: {
    zh: [
      { name: "首页", href: "/zh/" },
      { name: "文章", href: "/zh/posts/" },
      { name: "搜索", href: "/zh/search/" },
      { name: "归档", href: "/zh/archives/" },
      { name: "友链", href: "/zh/links/" },
      { name: "DMCC", href: "https://dmcc.wunai.top/", external: true },
    ],
    en: [
      { name: "Home", href: "/en/" },
      { name: "Posts", href: "/en/posts/" },
      { name: "Search", href: "/en/search/" },
      { name: "Archives", href: "/en/archives/" },
      { name: "Links", href: "/en/links/" },
      { name: "DMCC", href: "https://dmcc.wunai.top/", external: true },
    ],
  },
  i18n: {
    zh: { home: "首页", posts: "文章", tags: "标签", search: "搜索", archives: "归档", categories: "分类", prev: "上一篇", next: "下一篇", readingTime: "分钟阅读", words: "字", pinned: "置顶", aiWarning: "本文由 AI 生成，可能存在误区，斟酌阅读！！", comments: "评论", searchPlaceholder: "输入关键词搜索...", noResults: "没有找到相关结果。", allPosts: "全部文章", onThisPage: "本页目录", printSingle: "打印", mdDownload: "下载 MD", scrollDown: "向下滚动", continueReading: "继续阅读", links: "友链", linksIntro: "这里是一些朋友的站点。觉得本站有些意思、也想交换链接的话，欢迎通过页面底部的邮箱或 QQ 联系我，写上你的站名、地址和一句介绍就行。", email: "邮箱", github: "GitHub", bilibili: "哔哩哔哩", youtube: "YouTube", wechat: "微信", discord: "Discord", discordHint: "通过邮箱加我为好友", authorPrefix: "作者：", contactLabel: "欢迎随时来友好交流", contactBody: "仓库完全公开，欢迎 clone、参考与自定义修改（文章内容请注明出处）。发现问题或有想聊的，随时找我。", repoLabel: "本站仓库", groupLabel: "文章组", groupCount: "篇", groupBack: "返回文章组", thanks: "感谢你的阅读 :D", updates: "最近更新", settings: "设置", settingsHint: "这些设置只保存在当前浏览器（localStorage），不会上传。", palette: "配色方案", paletteCustom: "自定义", customAccent: "自选主色", readWidth: "阅读宽度", widthNarrow: "窄", widthNormal: "标准", widthWide: "宽", bgEffect: "背景动效", bgFull: "完整", bgDim: "减弱", bgOff: "关闭", acrylic: "亚克力材质", acrylicOn: "开（毛玻璃）", acrylicOff: "关（实色）", motion: "动画强度", motionFull: "完整", motionLite: "精简", motionOff: "关闭", resetSettings: "恢复默认" },
    en: { home: "Home", posts: "Posts", tags: "Tags", search: "Search", archives: "Archives", categories: "Categories", prev: "Previous", next: "Next", readingTime: "min read", words: "words", pinned: "Pinned", aiWarning: "This article was generated by AI and may contain inaccuracies. Read with caution!", comments: "Comments", searchPlaceholder: "Search posts...", noResults: "No results found.", allPosts: "All Posts", onThisPage: "On this page", printSingle: "Print", mdDownload: "Download MD", scrollDown: "Scroll down", continueReading: "Continue reading", links: "Links", linksIntro: "Some sites run by friends. If you'd like to exchange links, reach me via the email or QQ at the bottom of the page — just send your site name, URL and a one-line intro.", email: "Email", github: "GitHub", bilibili: "Bilibili", youtube: "YouTube", wechat: "WeChat", discord: "Discord", discordHint: "Add me via email", authorPrefix: "By ", contactLabel: "Say hi any time", contactBody: "The repo is public — feel free to clone it, learn from it and adapt it (please credit the source for article content). Found a bug, or just want to chat? Get in touch.", repoLabel: "Repository", groupLabel: "Collection", groupCount: "articles", groupBack: "Back to collection", thanks: "Thanks for reading :D", updates: "Recent updates", settings: "Settings", settingsHint: "Preferences are stored in this browser only (localStorage), never uploaded.", palette: "Color scheme", paletteCustom: "Custom", customAccent: "Custom accent", readWidth: "Reading width", widthNarrow: "Narrow", widthNormal: "Normal", widthWide: "Wide", bgEffect: "Background animation", bgFull: "Full", bgDim: "Dimmed", bgOff: "Off", acrylic: "Acrylic material", acrylicOn: "On (frosted)", acrylicOff: "Off (solid)", motion: "Animation level", motionFull: "Full", motionLite: "Lite", motionOff: "Off", resetSettings: "Reset to defaults" },
  },
};

// 阅读时长（分钟）：按 400 字/分钟估算，至少 1 分钟
export const WORDS_PER_MINUTE = 400;

export function readingMinutes(wordCount: number): number {
  return Math.max(1, Math.round(wordCount / WORDS_PER_MINUTE));
}
